name: Playwright Tests
on:
    workflow_dispatch:
jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: lts/*
            - name: Install dependencies
              run: npm ci
            - name: Install Playwright Browsers
              run: npx playwright install --with-deps
            - name: Run Playwright tests
              run: npx playwright test
            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
            - name: Execute TRCLI Action
              uses: gurock/trcli-action@main
              with:
                  host: 'https://demotestrail184.testrail.io'
                  username: 'giahuy1842001@gmail.com'
                  password: 'Test123456@'
                  project_id: 1
                  run_id: 1
                  case_matcher: 'name'
                  report_file_path: 'test-results/junit-report.xml'
                  auto_create_cases_yes: 'false'
